Homework is complete
m210/Lesson_3 pull request #1
Opened 2021-11-22 13:52 UTC by m210

2021-11-22 23:00 UTC, OKrylov requested changes
В целом отличная работа, по задачам все практически верно, оставил пару небольших замечаний по коду + есть замечания по логике некоторых задач.
Если будут вопросы - пишите.

2021-11-22 23:00 UTC, OKrylov commented on src/com/company/Main.java
> +        if((clientOS instanceof Double && (double) clientOS == 1.0) || (clientOS instanceof Integer && (int) clientOS == iOS))
обсуждали в чате, решение проще, как сделано во 2 задании: дроби здесь не должно быть, только 0 и 1

2021-11-23 04:57 UTC, m210 commented on src/com/company/Main.java
> +        int extraDistance = deliveryDistance - 20;
Хех, да...надо было проверить все-таки пройтись циклом, этот код тестил не долго))
Вот так будет получше: 
int extraDistance = deliveryDistance - 20;
int days = 1 + extraDistance / 40;
if(extraDistance > 0 && (extraDistance % 40) != 0)
 days++;

Меня смутило, что в условиях после 100км написано - и так аналогично....а писать условиями каждые 40км до бесконечности в принципе нереально, для этого нужен хотя бы цикл, поэтому решил написать формулой.

2021-11-23 04:59 UTC, m210 commented on src/com/company/Main.java
> +        else if(OS == AndroidOS)
Я в критерии оценки прочитал, что вложения не допускаются, поэтому переписал "по-сложному". Если бы не эта фраза, написал бы попроще, как и планировал изначально. А с другой стороны хороший пример, что не всегда код без вложений читается легче (как об этом сказано в видео-лекции)

2021-11-23 05:55 UTC, m210 commented on src/com/company/Main.java
> +        if((year % 4) == 0 || ((year % 100) == 0 && (year % 400) == 0)) {
Сделал новый коммит с bug фиксом :) Вообще эти високосные года сложно тестировать...проверял с 1900 по 2030, вроде совпадало.
Новый алгоритм проверял с 1700 года...вроде совпадает))

2021-11-24 22:37 UTC, OKrylov approved these changes
по исправлениям все отлично, замечаний по коду не имею

2021-11-24 22:37 UTC, OKrylov commented on src/com/company/Main.java
> +       else if(deliveryDistance >= 20 && deliveryDistance < 60)
можно упростить, убрав условие `deliveryDistance >= 20` поскольку данная ветка будет проверяться только в том случае, если условие выше не сработало. Аналогично и для ветки ниже

2021-11-27 22:59 UTC, OKrylov approved these changes
По дополнительным задачам все верно, логика реализовано корректно, замечаний по коду не имею

2021-11-27 22:59 UTC, OKrylov commented on src/com/company/Main.java
> +            bet += 0.5f;
хоть скобки здесь и избыточны, но они позволяют более явно отделить блоки условных операторов друг от друга 
```suggestion
        if(age < 23) {
            bet++;
        } else if(age < 30) {
            bet += 0.5f;
        }
```

2022-03-04 04:43 UTC, merged